name: Deploy to One.com

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'production'
        type: choice
        options:
        - production
        - preview

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build application
      run: npm run build:prod
      env:
        VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
        VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
        VITE_SITE_URL: ${{ secrets.VITE_SITE_URL }}
        VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
        VITE_BUILD_MODE: production
    
    - name: Deploy to One.com
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.ONECOM_FTP_HOST }}
        username: ${{ secrets.ONECOM_FTP_USER }}
        password: ${{ secrets.ONECOM_FTP_PASSWORD }}
        local-dir: ./dist/
        server-dir: ${{ github.event.inputs.environment == 'preview' && '/preview' || '/public_html' }}
        exclude: |
          **/.DS_Store
          **/Thumbs.db
          **/*.log
          **/.git*
          **/node_modules
          **/src
          **/public
        log-level: minimal
    
    - name: Deployment Success
      run: |
        echo "✅ Deployment completed successfully!"
        echo "🌐 Site URL: ${{ secrets.VITE_SITE_URL }}"
        echo "🎵 Choir Music Search is now live!"
